[package]
name = "rs-pmtxt2merged"
version = "0.1.0"
edition = "2024"

description = "Merge Prometheus metrics in text format"
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-pmtxt2merged"
homepage = "https://github.com/takanoriyanagitani/rs-pmtxt2merged"
documentation = "https://docs.rs/rs-pmtxt2merged/latest"
keywords = ["prometheus", "metrics", "merge"]

exclude = [
]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"


[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[[bin]]
name = "pmtxt2merged"

[dependencies.prometheus]
version = "0.14"
default-features = false
features = [
]

[dependencies.prometheus-parse]
version = "0.2"
default-features = false
features = [
]

[dependencies.chrono]
version = "0.4"
default-features = false
features = [
]

[dependencies.protobuf]
version = "3.7"
default-features = false
features = [
]
